runtime: nodejs20
instance_class: F1
env_variables:
  NODE_ENV: "production"
  DATABASE_URL: "postgresql://prisma.ezixvbacsmkrapsluemi:amodenapiovonotigelle@aws-0-us-west-1.pooler.supabase.com:6543/postgres?pgbouncer=true"
  DIRECT_URL: "postgresql://prisma.ezixvbacsmkrapsluemi:amodenapiovonotigelle@aws-0-us-west-1.pooler.supabase.com:5432/postgres"
  NEXT_PUBLIC_SUPABASE_URL: "https://ezixvbacsmkrapsluemi.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV6aXh2YmFjc21rcmFwc2x1ZW1pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxNDUxODAsImV4cCI6MjA2ODcyMTE4MH0.KvT5QzSDhiSdCDcOpmv30OCP7IHZfF4XVulB7ikp6IE"
  SUPABASE_SERVICE_ROLE_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV6aXh2YmFjc21rcmFwc2x1ZW1pIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1MzE0NTE4MCwiZXhwIjoyMDY4NzIxMTgwfQ.KACrTr9PeQ5aY-xQb6knA_sQahX8B5YNjF63XV0yX70"
  INGESTION_API_KEY: "fwYHzgThlT5p3KrmdFLdItkT6HtYIzSTQu5TWTZ1BJ3UQlfqjlI8vyu6inECBobMv9vfooYWiN3Xj0VSZNt7zBXVmnkY7JmipVxqbF2InIGXplErsoyKzHrEidUo8l6t"
  PUBSUB_PUSH_AUDIENCE: "https://finances-tracker-468805.uw.r.appspot.com/api/gmail-push"
  PUBSUB_PUSH_SA_EMAIL: "finances-tracker-468805@appspot.gserviceaccount.com"
  GOOGLE_OAUTH_CLIENT_ID: "791860226520-9ololktpfties604utdkmiami7fnm9hu.apps.googleusercontent.com"
  GOOGLE_OAUTH_CLIENT_SECRET: "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"
  GOOGLE_OAUTH_REDIRECT_URI: "http://localhost"
  GMAIL_ACCESS_TOKEN: "ya29.a0AQQ_BDSNwevlbDa4H9u0Y_gm_tHiEldBM6SR-a_JdyNdAGNuMOsEDLSxCDjeZ0mX3Ngt5cZAM0aUl3MIXmZKhc9bqZ-3El9Tr-_59m2BDh2joze6sHyeyXQ5Vveo6iB1w4cjNT3Xui3Y3vtbbAsqVZqwRIpL9QJDvAyitLo_ii0cgesXaEnhYnXS5P-8cmuA3_Al9ZgaCgYKAR8SARQSFQHGX2Mi7IrQBQASxDdHUnNv3DX2FA0206"
  GMAIL_REFRESH_TOKEN: "1//06mdeRvgzU7eXCgYIARAAGAYSNwF-L9Ird6ODMSpZepjYpClYarD1_rbsoJHsn1cM1vppOCePXwulZK4jgNOis9E_pUwaEmi0Nsk"
  GMAIL_EXPIRY_DATE: "1761023654546"
automatic_scaling:
  min_instances: 0
  max_instances: 1
  target_cpu_utilization: 0.5
  max_concurrent_requests: 40
